import type { TriangleData } from "../types";

export const umbrella: Omit<TriangleData, "phase">[] = [
    //bg
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 333, y: -115 },
            { x: 295, y: -89 },
            { x: 325, y: -200 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 240, y: -70 },
            { x: 295, y: -89 },
            { x: 317, y: -145 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 260, y: 55 },
            { x: 230, y: 100 },
            { x: 265, y: 75 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 260, y: 55 },
            { x: 230, y: 100 },
            { x: 195, y: 100 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 180, y: 130 },
            { x: 230, y: 100 },
            { x: 195, y: 100 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 180, y: 130 },
            { x: 170, y: 90 },
            { x: 195, y: 100 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 180, y: 130 },
            { x: 170, y: 90 },
            { x: 135, y: 85 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 180, y: 130 },
            { x: 180, y: 185 },
            { x: 135, y: 85 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: 160, y: 220 },
            { x: 180, y: 185 },
            { x: 157, y: 135 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: 160, y: 220 },
            { x: 100, y: 185 },
            { x: 157, y: 160 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: 70, y: 160 },
            { x: 100, y: 185 },
            { x: 157, y: 160 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 70, y: 160 },
            { x: 155, y: 125 },
            { x: 157, y: 160 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 70, y: 160 },
            { x: 155, y: 125 },
            { x: 137, y: 85 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 70, y: 160 },
            { x: 115, y: 88 },
            { x: 137, y: 85 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 70, y: 160 },
            { x: 115, y: 88 },
            { x: 90, y: 97 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 70, y: 160 },
            { x: 60, y: 115 },
            { x: 90, y: 97 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: 70, y: 160 },
            { x: 60, y: 115 },
            { x: 10, y: 97 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: 70, y: 160 },
            { x: 0, y: 135 },
            { x: 10, y: 97 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: 70, y: 160 },
            { x: 0, y: 135 },
            { x: -30, y: 165 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: -60, y: 145 },
            { x: 0, y: 135 },
            { x: -30, y: 165 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: -60, y: 145 },
            { x: -60, y: 95 },
            { x: -45, y: 143 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: 0, y: 140 },
            { x: -60, y: 95 },
            { x: -45, y: 143 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: 0, y: 140 },
            { x: -60, y: 95 },
            { x: 10, y: 60 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 70, y: 160 },
            { x: -9, y: 175 },
            { x: -30, y: 165 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 0, y: 173 },
            { x: -9, y: 175 },
            { x: 11, y: 223 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 0, y: 173 },
            { x: 72, y: 160 },
            { x: 11, y: 223 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 119, y: 200 },
            { x: 75, y: 160 },
            { x: 11, y: 223 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 119, y: 200 },
            { x: 32, y: 240 },
            { x: 11, y: 223 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    //end bg
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0059E6",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: -32, y: -67 },
            { x: -35, y: -40 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: -43, y: -17 },
            { x: -35, y: -40 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: -43, y: -17 },
            { x: -59, y: 11 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: -52, y: 20 },
            { x: -59, y: 11 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: -52, y: 20 },
            { x: -43, y: 35 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: -36, y: 50 },
            { x: -43, y: 35 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: -36, y: 50 },
            { x: -28, y: 75 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: -25, y: 90 },
            { x: -28, y: 75 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: -25, y: 90 },
            { x: -20, y: 90 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: 0, y: 93 },
            { x: -20, y: 90 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: 0, y: 93 },
            { x: 20, y: 99 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: 35, y: 107 },
            { x: 20, y: 99 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: 35, y: 107 },
            { x: 50, y: 119 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 50, y: 70 },
            { x: 65, y: 109 },
            { x: 50, y: 119 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 50, y: 70 },
            { x: 65, y: 109 },
            { x: 80, y: 100 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 50, y: 70 },
            { x: 50, y: 0 },
            { x: 80, y: 100 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 100, y: 92 },
            { x: 50, y: 0 },
            { x: 80, y: 100 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 100, y: 92 },
            { x: 50, y: 0 },
            { x: 123, y: 87 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 105, y: 15 },
            { x: 50, y: 0 },
            { x: 123, y: 87 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 105, y: 15 },
            { x: 50, y: 0 },
            { x: 115, y: 0 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 105, y: 15 },
            { x: 123, y: 87 },
            { x: 115, y: 0 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 128, y: 1 },
            { x: 123, y: 87 },
            { x: 115, y: 0 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 128, y: 1 },
            { x: 123, y: 87 },
            { x: 145, y: 5 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: 154, y: 7 },
            { x: 133, y: 53 },
            { x: 145, y: 5 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 105, y: -15 },
            { x: 50, y: 0 },
            { x: 115, y: 0 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 105, y: -15 },
            { x: 50, y: 0 },
            { x: 117, y: -35 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 105, y: -15 },
            { x: 117, y: 1 },
            { x: 117, y: -35 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 127, y: 1 },
            { x: 117, y: 1 },
            { x: 117, y: -35 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 128, y: -55 },
            { x: 50, y: 0 },
            { x: 117, y: -35 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 128, y: -55 },
            { x: 128, y: 5 },
            { x: 117, y: -35 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 128, y: -55 },
            { x: 128, y: 5 },
            { x: 145, y: 5 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 128, y: -55 },
            { x: 153, y: 6 },
            { x: 145, y: 5 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 128, y: -55 },
            { x: 50, y: 0 },
            { x: 120, y: -75 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 105, y: -75 },
            { x: 50, y: 0 },
            { x: 120, y: -75 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 105, y: -75 },
            { x: 50, y: 0 },
            { x: 90, y: -78 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 70, y: -86 },
            { x: 50, y: 0 },
            { x: 90, y: -78 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 70, y: -86 },
            { x: 50, y: 0 },
            { x: 50, y: -97 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 44, y: -100 },
            { x: 50, y: 0 },
            { x: 50, y: -97 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 44, y: -100 },
            { x: 50, y: 0 },
            { x: 30, y: -50 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 44, y: -100 },
            { x: 15, y: -50 },
            { x: 30, y: -50 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: 15, y: -50 },
            { x: 30, y: -50 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 50, y: 0 },
            { x: 15, y: -50 },
            { x: -10, y: -50 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 44, y: -100 },
            { x: 15, y: -50 },
            { x: -10, y: -50 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 44, y: -100 },
            { x: -23, y: -60 },
            { x: -10, y: -50 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 13, y: -82 },
            { x: -23, y: -60 },
            { x: -32, y: -68 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 164, y: -83 },
            { x: 197, y: -145 },
            { x: 180, y: -160 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 225, y: -190 },
            { x: 197, y: -145 },
            { x: 180, y: -160 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 225, y: -190 },
            { x: 170, y: -175 },
            { x: 180, y: -160 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 164, y: -83 },
            { x: 170, y: -175 },
            { x: 180, y: -160 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 164, y: -83 },
            { x: 170, y: -175 },
            { x: 150, y: -168 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 164, y: -83 },
            { x: 130, y: -160 },
            { x: 150, y: -168 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 146, y: -120 },
            { x: 130, y: -160 },
            { x: 118, y: -156 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 164, y: -83 },
            { x: 197, y: -143 },
            { x: 210, y: -130 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 225, y: -190 },
            { x: 197, y: -143 },
            { x: 210, y: -130 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 225, y: -190 },
            { x: 230, y: -103 },
            { x: 210, y: -130 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 164, y: -83 },
            { x: 230, y: -103 },
            { x: 210, y: -130 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 164, y: -83 },
            { x: 230, y: -103 },
            { x: 245, y: -80 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 225, y: -190 },
            { x: 230, y: -103 },
            { x: 245, y: -80 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 225, y: -190 },
            { x: 240, y: -133 },
            { x: 245, y: -80 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 250, y: -73 },
            { x: 240, y: -133 },
            { x: 245, y: -80 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 250, y: -73 },
            { x: 200, y: -81 },
            { x: 245, y: -80 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 250, y: -73 },
            { x: 265, y: -92 },
            { x: 245, y: -110 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 240, y: -143 },
            { x: 265, y: -92 },
            { x: 245, y: -110 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 250, y: -123 },
            { x: 265, y: -92 },
            { x: 275, y: -98 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 250, y: -123 },
            { x: 295, y: -108 },
            { x: 275, y: -98 }
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 250, y: -123 },
            { x: 295, y: -108 },
            { x: 240, y: -143 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 225, y: -190 },
            { x: 295, y: -108 },
            { x: 240, y: -143 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 225, y: -190 },
            { x: 295, y: -108 },
            { x: 315, y: -113 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 225, y: -190 },
            { x: 281, y: -148 },
            { x: 315, y: -113 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 317, y: -145 },
            { x: 281, y: -148 },
            { x: 315, y: -113 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 317, y: -145 },
            { x: 281, y: -148 },
            { x: 225, y: -190 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 317, y: -145 },
            { x: 321, y: -170 },
            { x: 225, y: -190 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 260, y: -198 },
            { x: 321, y: -170 },
            { x: 225, y: -190 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 260, y: -198 },
            { x: 321, y: -170 },
            { x: 300, y: -200 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 327, y: -200 },
            { x: 321, y: -170 },
            { x: 300, y: -200 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0059E6",
        rotation: 0,
        points: [
            { x: 327, y: -200 },
            { x: 278, y: -215 },
            { x: 300, y: -200 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0059E6",
        rotation: 0,
        points: [
            { x: 327, y: -200 },
            { x: 278, y: -215 },
            { x: 312, y: -215 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 302, y: -230 },
            { x: 278, y: -215 },
            { x: 312, y: -215 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 261, y: -199 },
            { x: 278, y: -215 },
            { x: 300, y: -200 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 261, y: -199 },
            { x: 278, y: -215 },
            { x: 222, y: -190 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 245, y: -220 },
            { x: 278, y: -215 },
            { x: 222, y: -190 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 245, y: -220 },
            { x: 278, y: -215 },
            { x: 260, y: -240 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 283, y: -270 },
            { x: 278, y: -215 },
            { x: 260, y: -240 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 283, y: -270 },
            { x: 278, y: -215 },
            { x: 302, y: -230 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 283, y: -270 },
            { x: 221, y: -200 },
            { x: 222, y: -190 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 283, y: -270 },
            { x: 221, y: -200 },
            { x: 219, y: -215 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 283, y: -270 },
            { x: 217, y: -230 },
            { x: 219, y: -215 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 283, y: -270 },
            { x: 217, y: -230 },
            { x: 213, y: -250 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 283, y: -270 },
            { x: 209, y: -270 },
            { x: 213, y: -250 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 260, y: -270 },
            { x: 209, y: -270 },
            { x: 207, y: -280 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 222, y: -190 },
            { x: 200, y: -250 },
            { x: 207, y: -280 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 180, y: -240 },
            { x: 200, y: -250 },
            { x: 207, y: -280 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 180, y: -240 },
            { x: 200, y: -250 },
            { x: 206, y: -230 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 180, y: -240 },
            { x: 160, y: -240 },
            { x: 207, y: -280 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 180, y: -240 },
            { x: 160, y: -240 },
            { x: 210, y: -220 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 180, y: -240 },
            { x: 207, y: -228 },
            { x: 210, y: -220 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 135, y: -243 },
            { x: 160, y: -240 },
            { x: 207, y: -280 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 222, y: -190 },
            { x: 160, y: -240 },
            { x: 135, y: -243 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 222, y: -190 },
            { x: 160, y: -240 },
            { x: 210, y: -220 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 222, y: -190 },
            { x: 160, y: -210 },
            { x: 135, y: -243 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 150, y: -200 },
            { x: 160, y: -210 },
            { x: 135, y: -243 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 150, y: -200 },
            { x: 160, y: -210 },
            { x: 222, y: -190 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 150, y: -200 },
            { x: 145, y: -185 },
            { x: 222, y: -190 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 145, y: -168 },
            { x: 145, y: -185 },
            { x: 222, y: -190 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 150, y: -200 },
            { x: 145, y: -185 },
            { x: 135, y: -243 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 145, y: -168 },
            { x: 145, y: -185 },
            { x: 116, y: -156 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 140, y: -210 },
            { x: 145, y: -185 },
            { x: 116, y: -156 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 140, y: -210 },
            { x: 135, y: -243 },
            { x: 130, y: -189 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 119, y: -76 },
            { x: 155, y: -102 },
            { x: 177, y: -49 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 173, y: -82 },
            { x: 163, y: -82 },
            { x: 177, y: -49 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 173, y: -82 },
            { x: 200, y: -80 },
            { x: 177, y: -49 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 228, y: -75 },
            { x: 200, y: -80 },
            { x: 177, y: -49 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 228, y: -75 },
            { x: 184, y: -15 },
            { x: 177, y: -49 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 119, y: -76 },
            { x: 184, y: -15 },
            { x: 177, y: -49 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 119, y: -76 },
            { x: 184, y: -15 },
            { x: 132, y: -49 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: 150, y: -3 },
            { x: 140, y: -43 },
            { x: 132, y: -49 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 150, y: -3 },
            { x: 140, y: -43 },
            { x: 184, y: -15 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 150, y: -3 },
            { x: 154, y: 5 },
            { x: 184, y: -15 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 157, y: 30 },
            { x: 154, y: 5 },
            { x: 184, y: -15 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 157, y: 30 },
            { x: 154, y: 5 },
            { x: 135, y: 50 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 157, y: 30 },
            { x: 125, y: 90 },
            { x: 135, y: 50 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: 157, y: 30 },
            { x: 125, y: 90 },
            { x: 145, y: 88 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: 157, y: 30 },
            { x: 165, y: 90 },
            { x: 145, y: 88 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 157, y: 30 },
            { x: 165, y: 90 },
            { x: 190, y: 97 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 157, y: 30 },
            { x: 207, y: 102 },
            { x: 190, y: 97 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 157, y: 30 },
            { x: 207, y: 102 },
            { x: 185, y: -15 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 255, y: 57 },
            { x: 207, y: 102 },
            { x: 185, y: -15 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 255, y: 57 },
            { x: 246, y: 35 },
            { x: 185, y: -15 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 228, y: 5 },
            { x: 246, y: 35 },
            { x: 185, y: -15 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 228, y: 5 },
            { x: 233, y: -5 },
            { x: 185, y: -15 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 237, y: -15 },
            { x: 233, y: -5 },
            { x: 185, y: -15 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 237, y: -15 },
            { x: 243, y: -27 },
            { x: 185, y: -15 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 196, y: -30 },
            { x: 243, y: -27 },
            { x: 185, y: -15 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 196, y: -30 },
            { x: 243, y: -27 },
            { x: 249, y: -45 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 196, y: -30 },
            { x: 252, y: -73 },
            { x: 249, y: -45 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 196, y: -30 },
            { x: 252, y: -73 },
            { x: 229, y: -73 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0066FF",
        rotation: 0,
        points: [
            { x: 280, y: -30 },
            { x: 257, y: -77 },
            { x: 252, y: -45 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0066FF",
        rotation: 0,
        points: [
            { x: 280, y: -30 },
            { x: 230, y: 5 },
            { x: 252, y: -45 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0059E6",
        rotation: 0,
        points: [
            { x: 280, y: -30 },
            { x: 230, y: 5 },
            { x: 295, y: -30 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0059E6",
        rotation: 0,
        points: [
            { x: 280, y: -30 },
            { x: 257, y: -77 },
            { x: 295, y: -30 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 342, y: -11 },
            { x: 257, y: -77 },
            { x: 295, y: -30 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 342, y: -11 },
            { x: 230, y: 5 },
            { x: 295, y: -30 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 342, y: -11 },
            { x: 257, y: -77 },
            { x: 310, y: -50 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 330, y: -55 },
            { x: 257, y: -77 },
            { x: 310, y: -50 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 330, y: -55 },
            { x: 342, y: -11 },
            { x: 310, y: -50 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 330, y: -55 },
            { x: 342, y: -11 },
            { x: 340, y: -65 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 330, y: -55 },
            { x: 257, y: -77 },
            { x: 340, y: -65 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 339, y: -85 },
            { x: 257, y: -77 },
            { x: 340, y: -65 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 339, y: -85 },
            { x: 257, y: -77 },
            { x: 337, y: -100 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 333, y: -115 },
            { x: 295, y: -89 },
            { x: 337, y: -100 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 342, y: -11 },
            { x: 230, y: 5 },
            { x: 295, y: 44 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 275, y: 70 },
            { x: 230, y: 5 },
            { x: 297, y: 44 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 275, y: 70 },
            { x: 257, y: 45 },
            { x: 263, y: 84 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 275, y: 70 },
            { x: 290, y: 87 },
            { x: 263, y: 84 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 275, y: 70 },
            { x: 290, y: 87 },
            { x: 303, y: 40 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: 347, y: 115 },
            { x: 290, y: 87 },
            { x: 303, y: 40 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: 347, y: 115 },
            { x: 343, y: -10 },
            { x: 303, y: 40 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 320, y: 103 },
            { x: 290, y: 87 },
            { x: 275, y: 178 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 255, y: 85 },
            { x: 290, y: 87 },
            { x: 275, y: 178 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 255, y: 85 },
            { x: 240, y: 130 },
            { x: 275, y: 178 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 255, y: 85 },
            { x: 240, y: 130 },
            { x: 225, y: 140 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 255, y: 85 },
            { x: 192, y: 130 },
            { x: 225, y: 140 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 255, y: 85 },
            { x: 192, y: 130 },
            { x: 180, y: 125 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 255, y: 85 },
            { x: 215, y: 107 },
            { x: 252, y: 70 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 255, y: 85 },
            { x: 260, y: 73 },
            { x: 252, y: 70 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 255, y: 85 },
            { x: 260, y: 73 },
            { x: 262, y: 85 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 275, y: 178 },
            { x: 240, y: 130 },
            { x: 225, y: 140 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 275, y: 178 },
            { x: 192, y: 130 },
            { x: 225, y: 140 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0059E6",
        rotation: 0,
        points: [
            { x: 275, y: 178 },
            { x: 192, y: 130 },
            { x: 225, y: 187 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0059E6",
        rotation: 0,
        points: [
            { x: 180, y: 124 },
            { x: 192, y: 130 },
            { x: 225, y: 187 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0059E6",
        rotation: 0,
        points: [
            { x: 180, y: 124 },
            { x: 192, y: 197 },
            { x: 225, y: 187 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0059E6",
        rotation: 0,
        points: [
            { x: 185, y: 154 },
            { x: 192, y: 197 },
            { x: 172, y: 203 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 108, y: 190 },
            { x: 140, y: 230 },
            { x: 172, y: 207 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 138, y: 250 },
            { x: 140, y: 230 },
            { x: 172, y: 207 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 138, y: 250 },
            { x: 140, y: 230 },
            { x: 108, y: 190 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 138, y: 250 },
            { x: 130, y: 270 },
            { x: 108, y: 190 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 138, y: 250 },
            { x: 130, y: 270 },
            { x: 172, y: 207 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 121, y: 290 },
            { x: 130, y: 270 },
            { x: 108, y: 190 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: 121, y: 290 },
            { x: 130, y: 270 },
            { x: 172, y: 207 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 108, y: 190 },
            { x: 90, y: 240 },
            { x: 37, y: 230 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 108, y: 190 },
            { x: 90, y: 240 },
            { x: 121, y: 290 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: 121, y: 290 },
            { x: 90, y: 240 },
            { x: 37, y: 230 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 121, y: 290 },
            { x: 90, y: 290 },
            { x: 37, y: 230 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#002680",
        rotation: 0,
        points: [
            { x: 70, y: 290 },
            { x: 90, y: 290 },
            { x: 37, y: 230 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 70, y: 290 },
            { x: 50, y: 290 },
            { x: 37, y: 230 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 25, y: 290 },
            { x: 50, y: 290 },
            { x: 37, y: 230 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 5, y: 290 },
            { x: -10, y: 245 },
            { x: 21, y: 247 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#001A66",
        rotation: 0,
        points: [
            { x: 5, y: 290 },
            { x: -10, y: 245 },
            { x: -82, y: 240 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 7, y: 220 },
            { x: -10, y: 245 },
            { x: 21, y: 247 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: 7, y: 220 },
            { x: -10, y: 245 },
            { x: -10, y: 170 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: -28, y: 220 },
            { x: -10, y: 245 },
            { x: -10, y: 170 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: -28, y: 220 },
            { x: -45, y: 225 },
            { x: -10, y: 170 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0040B3",
        rotation: 0,
        points: [
            { x: -28, y: 220 },
            { x: -45, y: 225 },
            { x: -10, y: 245 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: -65, y: 220 },
            { x: -45, y: 225 },
            { x: -10, y: 245 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#004DCC",
        rotation: 0,
        points: [
            { x: -65, y: 220 },
            { x: -45, y: 225 },
            { x: -10, y: 170 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#0059E6",
        rotation: 0,
        points: [
            { x: -65, y: 220 },
            { x: -85, y: 240 },
            { x: -10, y: 245 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: -65, y: 220 },
            { x: -85, y: 240 },
            { x: -85, y: 185 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: -65, y: 220 },
            { x: -65, y: 175 },
            { x: -85, y: 185 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: -65, y: 165 },
            { x: -65, y: 175 },
            { x: -85, y: 185 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#000D33",
        rotation: 0,
        points: [
            { x: -65, y: 165 },
            { x: -85, y: 175 },
            { x: -85, y: 185 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: -65, y: 165 },
            { x: -85, y: 175 },
            { x: -85, y: 155 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: -65, y: 165 },
            { x: -65, y: 145 },
            { x: -85, y: 155 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#00051A",
        rotation: 0,
        points: [
            { x: -65, y: 165 },
            { x: -65, y: 145 },
            { x: -45, y: 157 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: -65, y: 165 },
            { x: -65, y: 220 },
            { x: -45, y: 157 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#003399",
        rotation: 0,
        points: [
            { x: -10, y: 170 },
            { x: -65, y: 220 },
            { x: -45, y: 157 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#a5464a",
        rotation: 0,
        points: [
            { x: -74, y: 130 },
            { x: -85, y: 153 },
            { x: -60, y: 143 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#a5464a",
        rotation: 0,
        points: [
            { x: -74, y: 130 },
            { x: -85, y: 127 },
            { x: -109, y: 100 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#bf5255",
        rotation: 0,
        points: [
            { x: -74, y: 130 },
            { x: -85, y: 127 },
            { x: -85, y: 153 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#bf5255",
        rotation: 0,
        points: [
            { x: -109, y: 100 },
            { x: -85, y: 127 },
            { x: -85, y: 153 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#bf5255",
        rotation: 0,
        points: [
            { x: -109, y: 100 },
            { x: -100, y: 163 },
            { x: -85, y: 153 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#d95d60",
        rotation: 0,
        points: [
            { x: -109, y: 100 },
            { x: -100, y: 163 },
            { x: -150, y: 70 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#d95d60",
        rotation: 0,
        points: [
            { x: -138, y: 120 },
            { x: -100, y: 163 },
            { x: -150, y: 70 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#bf5255",
        rotation: 0,
        points: [
            { x: -138, y: 120 },
            { x: -100, y: 163 },
            { x: -132, y: 150 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#a5464a",
        rotation: 0,
        points: [
            { x: -126, y: 190 },
            { x: -100, y: 163 },
            { x: -132, y: 150 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#F4696B",
        rotation: 0,
        points: [
            { x: -126, y: 190 },
            { x: -160, y: 90 },
            { x: -150, y: 70 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#d95d60",
        rotation: 0,
        points: [
            { x: -126, y: 190 },
            { x: -160, y: 90 },
            { x: -172, y: 110 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#bf5255",
        rotation: 0,
        points: [
            { x: -126, y: 190 },
            { x: -186, y: 135 },
            { x: -172, y: 110 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#a5464a",
        rotation: 0,
        points: [
            { x: -126, y: 190 },
            { x: -186, y: 135 },
            { x: -198, y: 160 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#8b3a3f",
        rotation: 0,
        points: [
            { x: -160, y: 178 },
            { x: -205, y: 175 },
            { x: -198, y: 160 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#8b3a3f",
        rotation: 0,
        points: [
            { x: -220, y: 145 },
            { x: -205, y: 175 },
            { x: -198, y: 160 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#8b3a3f",
        rotation: 0,
        points: [
            { x: -220, y: 145 },
            { x: -182, y: 125 },
            { x: -198, y: 160 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#8b3a3f",
        rotation: 0,
        points: [
            { x: -220, y: 145 },
            { x: -182, y: 125 },
            { x: -240, y: 118 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#8b3a3f",
        rotation: 0,
        points: [
            { x: -250, y: 105 },
            { x: -182, y: 125 },
            { x: -240, y: 118 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#8b3a3f",
        rotation: 0,
        points: [
            { x: -250, y: 105 },
            { x: -182, y: 125 },
            { x: -213, y: 90 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#8b3a3f",
        rotation: 0,
        points: [
            { x: -180, y: 79 },
            { x: -182, y: 125 },
            { x: -213, y: 90 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#8b3a3f",
        rotation: 0,
        points: [
            { x: -180, y: 79 },
            { x: -182, y: 125 },
            { x: -150, y: 70 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#F4696B",
        rotation: 0,
        points: [
            { x: -180, y: 79 },
            { x: -197, y: 40 },
            { x: -150, y: 70 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#F4696B",
        rotation: 0,
        points: [
            { x: -180, y: 79 },
            { x: -197, y: 40 },
            { x: -240, y: 20 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#F4696B",
        rotation: 0,
        points: [
            { x: -180, y: 79 },
            { x: -220, y: 91 },
            { x: -240, y: 20 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#F4696B",
        rotation: 0,
        points: [
            { x: -237, y: 99 },
            { x: -220, y: 91 },
            { x: -240, y: 20 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#F4696B",
        rotation: 0,
        points: [
            { x: -237, y: 99 },
            { x: -254, y: 105 },
            { x: -240, y: 60 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#d95d60",
        rotation: 0,
        points: [
            { x: -169, y: -30 },
            { x: -197, y: 40 },
            { x: -150, y: 70 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#d95d60",
        rotation: 0,
        points: [
            { x: -169, y: -30 },
            { x: -197, y: 40 },
            { x: -225, y: 26 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#d95d60",
        rotation: 0,
        points: [
            { x: -200, y: 0 },
            { x: -237, y: 20 },
            { x: -225, y: 26 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#d95d60",
        rotation: 0,
        points: [
            { x: -169, y: -30 },
            { x: -103, y: 5 },
            { x: -150, y: 70 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#d95d60",
        rotation: 0,
        points: [
            { x: -137, y: -14 },
            { x: -103, y: 5 },
            { x: -89, y: -13 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#a5464a",
        rotation: 0,
        points: [
            { x: -72, y: 26 },
            { x: -103, y: 5 },
            { x: -89, y: -13 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#a5464a",
        rotation: 0,
        points: [
            { x: -72, y: 26 },
            { x: -103, y: 5 },
            { x: -150, y: 70 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#a5464a",
        rotation: 0,
        points: [
            { x: -72, y: 26 },
            { x: -46, y: 57 },
            { x: -150, y: 70 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#572329",
        rotation: 0,
        points: [
            { x: -55, y: 96 },
            { x: -46, y: 57 },
            { x: -150, y: 70 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
    {
        x: 0,
        y: 0,
        size: .7,
        color: "#572329",
        rotation: 0,
        points: [
            { x: -55, y: 96 },
            { x: -59, y: 140 },
            { x: -150, y: 70 },
        ],
        startX: 0,      
        startY: 0,
        scatterX: 0,   
        scatterY: 0,
        scale: 3,
        z: -3
    },
];
